pos(interval(-20)).
pos(interval(-14)).
pos(interval(19)).
pos(interval(-27)).
pos(interval(-15)).
pos(interval(-19)).
pos(interval(13)).
pos(interval(-21)).
pos(interval(-34)).
pos(interval(-9)).
pos(interval(-35)).
pos(interval(-8)).
pos(interval(-16)).
pos(interval(9)).
pos(interval(-11)).
pos(interval(4)).
pos(interval(-29)).
pos(interval(-19)).
pos(interval(-36)).
pos(interval(23)).
pos(interval(5)).
pos(interval(-30)).
pos(interval(-28)).
pos(interval(-19)).
pos(interval(9)).
pos(interval(7)).
pos(interval(-1)).
pos(interval(12)).
pos(interval(2)).
pos(interval(-29)).
neg(interval(-40)).
neg(interval(26)).
neg(interval(29)).
neg(interval(-48)).
neg(interval(28)).
neg(interval(50)).
neg(interval(44)).
neg(interval(48)).
neg(interval(29)).
neg(interval(-43)).
neg(interval(40)).
neg(interval(47)).
neg(interval(-41)).
neg(interval(45)).
neg(interval(-48)).
neg(interval(50)).
neg(interval(37)).
neg(interval(24)).
neg(interval(26)).
neg(interval(26)).
neg(interval(-42)).
neg(interval(47)).
neg(interval(25)).
neg(interval(27)).
neg(interval(29)).
neg(interval(-47)).
neg(interval(34)).
neg(interval(40)).
neg(interval(32)).
neg(interval(49)).
